version: '2.3'

services:

  node:
    build:
      context: .
      target: 'dev'
    ports:
      - "3006:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/app:delegated
    environment:
      - REACT_APP_API=${REACT_APP_API}
    healthcheck:
      disable: true